In [1]:

import pandas as pd
import os

In [668]:
files = [f for f in os.listdir("./data") if os.path.isfile(os.path.join("./data", f))]

In [669]:

users_filepath = os.path.join("./data", files[0])
# print(users_filepath)
users_xlx = pd.ExcelFile(users_filepath)


# Initialize an empty list to hold DataFrames
dfs = []

# Loop through each sheet in the Excel file
for sheet_name in users_xlx.sheet_names:
    # Load the sheet into a DataFrame
    r_df = pd.read_excel(users_filepath, sheet_name=sheet_name)
    r_df.rename(columns={'Unnamed: 0': 'Name', 'Unnamed: 1': 'Email'}, inplace=True)
    # Add a new column 'BU' with the value as the sheet name
    r_df['BU'] = sheet_name
    r_df['Email'] = r_df['Email'].str.strip().str.replace(',', '.')
    
    # Append the DataFrame to the list
    dfs.append(r_df)

# Concatenate all DataFrames into one
df = pd.concat(dfs, ignore_index=True)
# Rename columns 'Unnamed: 0' and 'Unnamed: 1' to 'name' and 'email'
df.head(10)

,Name,Email,Folder Xây dựng KH PRJ,Nhập liệu thẻ F,Nhập liệu thẻ C,Nhập liệu thẻ P,Nhập liệu thẻ L,PIC tổng hợp BSC KPI,BLĐ ĐV,PTK,BU
0,Trần Thị Thu Trang,TrangTTT@gemadept.com.vn,E,NaN,NaN,E,E,E-all,E-all,E-all,ADM
1,Đỗ Thị Hoàng Thư,thudth@gemadept.com.vn,E,NaN,NaN,E,E,E-all,NaN,NaN,ADM
2,Phan Thị Thanh Nga,NgaPT@gemadept.com.vn,E,NaN,NaN,E,E,E-all,NaN,NaN,ADM
3,Nguyễn Minh Nguyệt,nguyetminh@gemadept.com.vn,V,NaN,NaN,NaN,NaN,NaN,E-all,E-all,ACC
4,Khoa Năng Lưu,luukn@gemadept.com.vn,V,NaN,E,NaN,E,E-all,NaN,NaN,ACC
5,Vũ Thị Anh Thư,thuvta@gemadept.com.vn,V,NaN,E,NaN,NaN,NaN,NaN,NaN,ACC
6,Bùi Thị Huyền Trang,trangbth@gemadept.com.vn,V,E,NaN,NaN,NaN,NaN,NaN,NaN,ACC
7,Đinh Thị Thúy Anh,anhdtt@gemadept.com.vn,V,E,E,E,E,E-all,NaN,NaN,ACC
8,Nguyễn Thị Minh Thủy,Xunglh@gemadept.com.vn,NaN,E,NaN,NaN,NaN,NaN,NaN,NaN,ACC
9,Nguyễn Thị Ngọc Cẩm,camntn@gemadept.com.vn,NaN,E,NaN,E,NaN,NaN,NaN,NaN,ACC

In [670]:
duplicates_df = df[df.duplicated()]
duplicates_df

Empty DataFrame
Columns: [Name, Email, Folder Xây dựng KH PRJ, Nhập liệu thẻ F, Nhập liệu thẻ C, Nhập liệu thẻ P, Nhập liệu thẻ L, PIC tổng hợp BSC KPI, BLĐ ĐV, PTK, BU]
Index: []

In [671]:
# Custom mapping based on your examples
bu_mapping = {
    "Khối MN": "Khối PIP",
    "PRIR": "IR-PR",
    "NĐV": "NDV",
    # Add any other specific mappings if needed
}

# Replace BU values based on the custom mapping
df['BU'] = df['BU'].replace(bu_mapping)
df['BU'] = df['BU'].replace({'R&amp;D': 'R&D'})
df.head(1000)

,Name,Email,Folder Xây dựng KH PRJ,Nhập liệu thẻ F,Nhập liệu thẻ C,Nhập liệu thẻ P,Nhập liệu thẻ L,PIC tổng hợp BSC KPI,BLĐ ĐV,PTK,BU
0,Trần Thị Thu Trang,TrangTTT@gemadept.com.vn,E,NaN,NaN,E,E,E-all,E-all,E-all,ADM
1,Đỗ Thị Hoàng Thư,thudth@gemadept.com.vn,E,NaN,NaN,E,E,E-all,NaN,NaN,ADM
2,Phan Thị Thanh Nga,NgaPT@gemadept.com.vn,E,NaN,NaN,E,E,E-all,NaN,NaN,ADM
3,Nguyễn Minh Nguyệt,nguyetminh@gemadept.com.vn,V,NaN,NaN,NaN,NaN,NaN,E-all,E-all,ACC
4,Khoa Năng Lưu,luukn@gemadept.com.vn,V,NaN,E,NaN,E,E-all,NaN,NaN,ACC
...,...,...,...,...,...,...,...,...,...,...,...
173,Đỗ Minh Châu,ChauDM@mekonglogs.com,E-All,E-All,E-All,NaN,NaN,E-All,E-All,NaN,MKL
174,Chu Thị Kim Anh,kimanh@mekonglogs.com,E-All,E-All,E-All,NaN,NaN,E-All,NaN,NaN,MKL
175,Tăng Thị Anh Thư,ThuTTA@mekonglogs.com,E-All,E-All,E-All,NaN,NaN,E-All,NaN,NaN,MKL
176,Diệp Thiền Minh,MinhDT@mekonglogs.com,E-All,E-All,E-All,NaN,NaN,E-All,NaN,NaN,MKL
177,Phạm Quốc Long,LongPQ@gemadept.com.vn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,E-ALL,MKL

In [672]:
# Select only the 'email' and 'BU' columns
df_filtered = df[['Email', 'BU']]

# Export to an Excel file
df_filtered.to_excel('check_email_bu.xlsx', index=False)

print("Data exported successfully!")

Data exported successfully!

In [673]:
# Extract unique values from the 'BU' column
unique_bu = df['BU'].dropna().unique()

# Create a new DataFrame with the unique 'BU' values
unique_bu_df = pd.DataFrame(unique_bu, columns=['BU'])

# Export the unique 'BU' values to an Excel file
unique_bu_df.to_excel('check_unique_bu.xlsx', index=False)

print("Unique BU values exported successfully!")

Unique BU values exported successfully!

In [674]:
folders_filepath = os.path.join("./data", files[1])
folders_df = pd.read_csv(folders_filepath)
folders_df.head(10)

    /sites/BSCKPI/Shared Documents/2025/1. TẬP ĐOÀN;
0  /sites/BSCKPI/Shared Documents/2025/1. TẬP ĐOÀ...
1  /sites/BSCKPI/Shared Documents/2025/1. TẬP ĐOÀ...
2  /sites/BSCKPI/Shared Documents/2025/1. TẬP ĐOÀ...
3  /sites/BSCKPI/Shared Documents/2025/1. TẬP ĐOÀ...
4  /sites/BSCKPI/Shared Documents/2025/1. TẬP ĐOÀ...
5  /sites/BSCKPI/Shared Documents/2025/1. TẬP ĐOÀ...
6  /sites/BSCKPI/Shared Documents/2025/1. TẬP ĐOÀ...
7  /sites/BSCKPI/Shared Documents/2025/1. TẬP ĐOÀ...
8  /sites/BSCKPI/Shared Documents/2025/1. TẬP ĐOÀ...
9  /sites/BSCKPI/Shared Documents/2025/1. TẬP ĐOÀ...

In [675]:
# Define a function to determine the correct permission
def map_permission(value):
    if value:
        value_lower = value.strip().lower()
        if value_lower in ['e', 'edit', 'edit-all', 'e-all', 'e - all', 'x']:
            return 'Edit'
        elif value_lower in ['v', 'view', 'view-all', 'v-all']:
            return 'View'
    return value  # Default: keep the original value if not matched

In [676]:


# Simplified mapping for the columns
column_name_map = {
    'Nhập liệu thẻ F': 'f_df',
    'Nhập liệu thẻ C': 'c_df',
    'Nhập liệu thẻ P': 'p_df',
    'Nhập liệu thẻ L': 'l_df',
}


# Loop through each column and create the necessary DataFrames
for column, simplified_name in column_name_map.items():
    # Create the new DataFrame with 'Email', 'BU', and the current column, dropping NaNs
    new_df = df[['Email', 'BU', column]].dropna(subset=[column])
    
    # Rename the current column to 'Permission'
    new_df.rename(columns={column: 'Permission'}, inplace=True)
    # Normalize all values in the 'Permission' column to "Edit"
    new_df['Permission'] = new_df['Permission'].apply(map_permission)

    # Assign the DataFrame to a variable with the simplified name
    globals()[simplified_name] = new_df

    # Save the DataFrame to an Excel file with the format "rw_simplified_name.xlsx"
    filename = f'rw_{simplified_name}.xlsx'
    # Using ExcelWriter to format as a table
    with pd.ExcelWriter(filename, engine='xlsxwriter') as writer:
        new_df.to_excel(writer, index=False, sheet_name="data")

        # Access the xlsxwriter workbook and sheet
        workbook = writer.book
        worksheet = writer.sheets["data"]

        # Add a table format for the data
        worksheet.add_table(0, 0, new_df.shape[0], new_df.shape[1] - 1,
                            {'columns': [{'header': col} for col in new_df.columns]})

    print(f'Saved {filename}')  # Optional, to confirm saving


# Now you can check the saved files in the current directory

Saved rw_f_df.xlsx
Saved rw_c_df.xlsx
Saved rw_p_df.xlsx
Saved rw_l_df.xlsx

In [677]:

# Layer 2 folders mapping for BU to layer2 folder
bu_to_layer2_mapping = {
    "ADM": "10.2. ADM",
    "ACC": "10.4. ACC",
    "CĐS": "10.14. CĐS",
    "FIN": "10.3. FIN",
    "RM1": "10.10. RM1",
    "RM2": "10.11. RM2",
    "R&D": "10.6. R&D",
    "IR-PR": "10.7. IR-PR",
    "IT": "10.5. IT",
    "HR": "10.9. HR",
    "MKT": "10.1. MKT",
    "PRC": "10.12. PRC",
    "HSSE": "10.13. HSSE",
    "Khối PIP": "3. Khối PIP",
    "PIP": "3.1. PIP",
    "BDP": "3.2. BDP",
    "PME": "3.4. PME",
    "BTC": "3.3. BTC",
    "Khối HP": "2. Khối HP",
    "NDV": "2.1. NDV",
    "NHI": "2.2. NHI",
    "GPS": "2.3. GPS",
    "GNL": "2.5. GNL",
    "DQP": "4. DQP",
    "GCC": "5. GCC",
    "GLC": "7.1. GLC",
    "GSC": "8.1. GSC",
    "GIC": "7.2. MKL",
    "KGL": "9.2. KGL",
    "MKL": "7.2. MKL",
}

# Reverse the mapping from Layer2Folder to BU
layer2_to_bu_mapping = {v: k for k, v in bu_to_layer2_mapping.items()}

# Folder RelativeURL templates
folder_url_templates = {
    'Nhập liệu thẻ F': '/sites/BSCKPI/Shared Documents/2025/{}/2. Thực hiện BSC.KPI/2. 2025 - {} - Thẻ F',
    'Nhập liệu thẻ C': '/sites/BSCKPI/Shared Documents/2025/{}/2. Thực hiện BSC.KPI/3. 2025 - {} - Thẻ C',
    'Nhập liệu thẻ P': '/sites/BSCKPI/Shared Documents/2025/{}/2. Thực hiện BSC.KPI/4. 2025 - {} - Thẻ P',
    'Nhập liệu thẻ L': '/sites/BSCKPI/Shared Documents/2025/{}/2. Thực hiện BSC.KPI/5. 2025 - {} - Thẻ L',
}

# List to hold all DataFrames
all_dfs = []

# Loop through each column and create the necessary DataFrames
for column, simplified_name in column_name_map.items():
    # Create the new DataFrame with 'Email', 'BU', and the current column, dropping NaNs
    new_df = df[['Email', 'BU', column]].dropna(subset=[column])
    # Rename the current column to 'Permission'
    new_df.rename(columns={column: 'Permission'}, inplace=True)
    # Normalize all values in the 'Permission' column to "Edit"
    new_df['Permission'] = new_df['Permission'].apply(map_permission)

    # Map BU to the corresponding layer2 folder using the 'bu_to_layer2_mapping' dictionary
    new_df['Layer2Folder'] = new_df['BU'].map(bu_to_layer2_mapping)

    # Generate the RelativeURL using the Layer2Folder and its corresponding BU key
    new_df['RelativeURL'] = new_df['Layer2Folder'].apply(
        lambda folder: folder_url_templates[column].format(folder, layer2_to_bu_mapping.get(folder, 'Invalid BU'))
        if folder else 'Invalid BU'
    )

    # Assign the DataFrame to a variable with the simplified name
    globals()[simplified_name] = new_df
    # Append the DataFrame to the list
    all_dfs.append(new_df)


    filename = f'url_{simplified_name}.xlsx'
    # Using ExcelWriter to format as a table
    with pd.ExcelWriter(filename, engine='xlsxwriter') as writer:
        new_df.to_excel(writer, index=False, sheet_name="data")

        # Access the xlsxwriter workbook and sheet
        workbook = writer.book
        worksheet = writer.sheets["data"]

        # Add a table format for the data
        worksheet.add_table(0, 0, new_df.shape[0], new_df.shape[1] - 1,
                            {'columns': [{'header': col} for col in new_df.columns]})

    print(f'Saved {filename}')  # Optional, to confirm saving

# Now you can print any of the simplified DataFrames
print(f_df.head(10))  # For example, to view the 'f_df' DataFrame

Saved url_f_df.xlsx
Saved url_c_df.xlsx
Saved url_p_df.xlsx
Saved url_l_df.xlsx
                        Email        BU Permission Layer2Folder  \
6    trangbth@gemadept.com.vn       ACC       Edit    10.4. ACC
7      anhdtt@gemadept.com.vn       ACC       Edit    10.4. ACC
8      Xunglh@gemadept.com.vn       ACC       Edit    10.4. ACC
9      camntn@gemadept.com.vn       ACC       Edit    10.4. ACC
45    Thaontt@gemadept.com.vn     IR-PR       Edit  10.7. IR-PR
46  nguyenanh@gemadept.com.vn     IR-PR       Edit  10.7. IR-PR
47    DieuAnh@gemadept.com.vn     IR-PR       Edit  10.7. IR-PR
59   duongdtt@gemadept.com.vn       MKT       Edit    10.1. MKT
72     DungHTT.ACC@pip.com.vn  Khối PIP       Edit  3. Khối PIP
79     ThaoCTK.ACC@pip.com.vn       PIP       Edit     3.1. PIP

                                          RelativeURL
6   /sites/BSCKPI/Shared Documents/2025/10.4. ACC/...
7   /sites/BSCKPI/Shared Documents/2025/10.4. ACC/...
8   /sites/BSCKPI/Shared Documents/2025/10.4. ACC/...
9   /sites/BSCKPI/Shared Documents/2025/10.4. ACC/...
45  /sites/BSCKPI/Shared Documents/2025/10.7. IR-P...
46  /sites/BSCKPI/Shared Documents/2025/10.7. IR-P...
47  /sites/BSCKPI/Shared Documents/2025/10.7. IR-P...
59  /sites/BSCKPI/Shared Documents/2025/10.1. MKT/...
72  /sites/BSCKPI/Shared Documents/2025/3. Khối PI...
79  /sites/BSCKPI/Shared Documents/2025/3.1. PIP/2...

In [678]:
# Combine all DataFrames into one
combined_df = pd.concat(all_dfs, ignore_index=True)
combined_df = combined_df.drop('Layer2Folder', axis=1)
# Save the combined DataFrame to a single Excel file
combined_filename = 'consolidated_url_fcpl.xlsx'
with pd.ExcelWriter(combined_filename, engine='xlsxwriter') as writer:
    combined_df.to_excel(writer, index=False, sheet_name='data')

    workbook = writer.book
    worksheet = writer.sheets['data']

    # Add a table format for the combined data
    worksheet.add_table(0, 0, combined_df.shape[0], combined_df.shape[1] - 1,
                        {'columns': [{'header': col} for col in combined_df.columns]})

print(f'Saved combined data to {combined_filename}')  # To confirm saving the combined file

Saved combined data to consolidated_url_fcpl.xlsx

In [679]:
# KH PRJ - Extract relevant rows
khprj_df = df.dropna(subset=['Folder Xây dựng KH PRJ']).copy()  # Create a copy to avoid SettingWithCopyWarning

# Rename the relevant column to 'Permission'
khprj_df.rename(columns={'Folder Xây dựng KH PRJ': 'Permission'}, inplace=True)

# Keep only required columns
khprj_df = khprj_df[['Email', 'BU', 'Permission']]

# Optional: Display the first 50 rows for verification
# khprj_df.head(50)
khprj_df.count()

Email         109
BU            109
Permission    109
dtype: int64

In [680]:
# Folder RelativeURL templates for KH PRJ
khprj_folder_url_templates = {
    'Folder Xây dựng KH PRJ': '/sites/BSCKPI/Shared Documents/2025/{}/1. Xây dựng kế hoạch PRJ'
}

# Initialize an empty list to store the new rows
final_khprj_rows = []

# Iterate over each row in the khprj_df
for index, row in khprj_df.iterrows():
    # First, process the Permission value before URL generation
    processed_permission = map_permission(row['Permission'])

    # Generate new row based on the folder_url_template for KH PRJ
    for folder_name, folder_url_template in khprj_folder_url_templates.items():
        # Create a new row by copying the original one
        new_row = row.copy()

        # Generate the RelativeURL using the 'BU' column (or any other appropriate column)
        relative_url = folder_url_template.format(row['BU'])
        
        # Add the processed Permission and RelativeURL to the new row
        new_row['Permission'] = processed_permission
        new_row['RelativeURL'] = relative_url

        # Add the new row to the list
        final_khprj_rows.append(new_row)

# Convert the list of rows into a new DataFrame
khprj_df_extended = pd.DataFrame(final_khprj_rows)

# Save to Excel
filename = 'url_khprj.xlsx'
with pd.ExcelWriter(filename, engine='xlsxwriter') as writer:
    khprj_df_extended.to_excel(writer, index=False, sheet_name="data")

    # Access the xlsxwriter workbook and sheet
    workbook = writer.book
    worksheet = writer.sheets["data"]

    # Add a table format for the data
    worksheet.add_table(0, 0, khprj_df_extended.shape[0], khprj_df_extended.shape[1] - 1,
                        {'columns': [{'header': col} for col in khprj_df_extended.columns]})

    print(f'Saved {filename}')  # Optional, to confirm saving

Saved url_khprj.xlsx

In [681]:
# PIC Tong hop
pic_bsckpi_df = df.dropna(subset=['PIC tổng hợp BSC KPI']).copy()

# Rename the relevant column to 'Permission'
pic_bsckpi_df.rename(columns={'PIC tổng hợp BSC KPI': 'Permission'}, inplace=True)

# Keep only required columns
pic_bsckpi_df = pic_bsckpi_df[['Email', 'BU', 'Permission']]

# Optional: Print the first few rows of the new DataFrame
print(pic_bsckpi_df.head(100))

                        Email   BU Permission
0    TrangTTT@gemadept.com.vn  ADM      E-all
1      thudth@gemadept.com.vn  ADM      E-all
2       NgaPT@gemadept.com.vn  ADM      E-all
4       luukn@gemadept.com.vn  ACC      E-all
7      anhdtt@gemadept.com.vn  ACC      E-all
..                        ...  ...        ...
172        thaontn@kgl.com.vn  KGL      E-All
173     ChauDM@mekonglogs.com  MKL      E-All
174     kimanh@mekonglogs.com  MKL      E-All
175     ThuTTA@mekonglogs.com  MKL      E-All
176     MinhDT@mekonglogs.com  MKL      E-All

[94 rows x 3 columns]

In [682]:


# Folder RelativeURL templates
bsckpi_folder_url_templates = {
    'PIC tổng hợp BSC KPI': '/sites/BSCKPI/Shared Documents/2025/{}/2. Thực hiện BSC.KPI/1. 2025 - {} - Tổng BSC.KPI',
}

# Map BU to the corresponding layer2 folder using the 'bu_to_layer2_mapping' dictionary
pic_bsckpi_df['Layer2Folder'] = pic_bsckpi_df['BU'].map(bu_to_layer2_mapping)

# Generate the RelativeURL using the Layer2Folder and its corresponding BU key
pic_bsckpi_df['RelativeURL'] = pic_bsckpi_df['Layer2Folder'].apply(
    lambda folder: bsckpi_folder_url_templates['PIC tổng hợp BSC KPI'].format(folder, layer2_to_bu_mapping.get(folder, 'Invalid BU'))
    if folder else 'Invalid BU'
)

pic_bsckpi_df['Permission'] = pic_bsckpi_df['Permission'].apply(map_permission)

pic_bsckpi_df = pic_bsckpi_df.drop('Layer2Folder', axis=1)
filename = f'url_bsckpi_df.xlsx'

# Using ExcelWriter to format as a table
with pd.ExcelWriter(filename, engine='xlsxwriter') as writer:
    pic_bsckpi_df.to_excel(writer, index=False, sheet_name="data")

    # Access the xlsxwriter workbook and sheet
    workbook = writer.book
    worksheet = writer.sheets["data"]

    # Add a table format for the data
    worksheet.add_table(0, 0, pic_bsckpi_df.shape[0], pic_bsckpi_df.shape[1] - 1,
                        {'columns': [{'header': col} for col in pic_bsckpi_df.columns]})

    print(f'Saved {filename}')  # Optional, to confirm saving

Saved url_bsckpi_df.xlsx

In [683]:
# # Folder RelativeURL templates for additional rows
# folder_url_templates = {
#     'Nhập liệu thẻ F': '/sites/BSCKPI/Shared Documents/2025/{}/2. Thực hiện BSC.KPI/2. 2025 - {} - Thẻ F',
#     'Nhập liệu thẻ C': '/sites/BSCKPI/Shared Documents/2025/{}/2. Thực hiện BSC.KPI/3. 2025 - {} - Thẻ C',
#     'Nhập liệu thẻ P': '/sites/BSCKPI/Shared Documents/2025/{}/2. Thực hiện BSC.KPI/4. 2025 - {} - Thẻ P',
#     'Nhập liệu thẻ L': '/sites/BSCKPI/Shared Documents/2025/{}/2. Thực hiện BSC.KPI/5. 2025 - {} - Thẻ L',
# }

# # Initialize an empty list to store the new rows
# final_rows = []

# # Iterate over each row in the DataFrame
# for index, row in pic_bsckpi_df.iterrows():
#     # Add the original row first
#     final_rows.append(row)

#     # Generate 4 new rows based on the folder_url_templates
#     for folder_name, folder_url_template in folder_url_templates.items():
#         # Create a new row by copying the original one
#         new_row = row.copy()

#         # Generate the RelativeURL using the Layer2Folder and its corresponding BU key
#         new_row['RelativeURL'] = folder_url_template.format(row['Layer2Folder'], layer2_to_bu_mapping.get(row['Layer2Folder'], 'Invalid BU'))
#         new_row['Permission'] = 'Edit'  # Assuming 'Edit' as the value for all rows

#         # Add the new row right after the original row
#         final_rows.append(new_row)

# # Convert the list of rows into a new DataFrame
# pic_bsckpi_df_extended = pd.DataFrame(final_rows)
# pic_bsckpi_df_extended = pic_bsckpi_df_extended.drop('Layer2Folder', axis=1)
# # Save to Excel
# filename = 'consolidated_url_bsckpi.xlsx'
# with pd.ExcelWriter(filename, engine='xlsxwriter') as writer:
#     pic_bsckpi_df_extended.to_excel(writer, index=False, sheet_name="data")

#     # Access the xlsxwriter workbook and sheet
#     workbook = writer.book
#     worksheet = writer.sheets["data"]

#     # Add a table format for the data
#     worksheet.add_table(0, 0, pic_bsckpi_df_extended.shape[0], pic_bsckpi_df_extended.shape[1] - 1,
#                         {'columns': [{'header': col} for col in pic_bsckpi_df_extended.columns]})

#     print(f'Saved {filename}')  # Optional, to confirm saving

In [684]:
# BLD PBDV
bld_df = df.dropna(subset=['BLĐ ĐV']).copy()
# Rename the relevant column to 'Permission'
bld_df.rename(columns={'BLĐ ĐV': 'Permission'}, inplace=True)
bld_df = bld_df[['Email', 'BU', 'Permission']]
# Optional: Print the first few rows of the new DataFrame
bld_df.head(15)
# bld_df.count()

                         Email   BU Permission
0     TrangTTT@gemadept.com.vn  ADM      E-all
3   nguyetminh@gemadept.com.vn  ACC      E-all
13       huypq@gemadept.com.vn  CĐS      E-all
14     oanhpnh@gemadept.com.vn  CĐS      E-all
15    huongbtt@gemadept.com.vn  FIN      E-all
24      bacvth@gemadept.com.vn  RM1      E-all
25      anhvtk@gemadept.com.vn  RM1      E-all
34       NgaTQ@gemadept.com.vn  RM2      E-all
35        HaNB@gemadept.com.vn  RM2      E-all
39    HuongBTT@gemadept.com.vn  R&D          E
40       huehl@gemadept.com.vn  R&D          E
48       loccq@gemadept.com.vn   IT      E-all
49      cangpt@gemadept.com.vn   IT      E-all
50      tuancq@gemadept.com.vn   IT      E-all
51      anhttp@gemadept.com.vn   HR      E-all

In [685]:

# Folder RelativeURL templates
bld_folder_url_templates = { 
    'BLD': '/sites/BSCKPI/Shared Documents/2025/{}', 
}

# Generate the RelativeURL using the BU -> Layer2 mapping
bld_df['Layer2Folder'] = bld_df['BU'].map(bu_to_layer2_mapping)

# Generate URL only if a valid mapping exists
bld_df['RelativeURL'] = bld_df['Layer2Folder'].apply(
    lambda folder: bld_folder_url_templates['BLD'].format(folder) if folder else 'Invalid BU'
)

bld_df['Permission'] = bld_df['Permission'].apply(map_permission)
# Optional: Print the first few rows to verify
print(bld_df.head(15))

# Save to Excel
filename = 'url_bld.xlsx'
with pd.ExcelWriter(filename, engine='xlsxwriter') as writer:
    bld_df.to_excel(writer, index=False, sheet_name="data")

    # Access the xlsxwriter workbook and sheet
    workbook = writer.book
    worksheet = writer.sheets["data"]

    # Add a table format for the data
    worksheet.add_table(0, 0, bld_df.shape[0], bld_df.shape[1] - 1,
                        {'columns': [{'header': col} for col in bld_df.columns]})

    print(f'Saved {filename}')  # Optional, to confirm saving

                         Email   BU Permission Layer2Folder  \
0     TrangTTT@gemadept.com.vn  ADM       Edit    10.2. ADM
3   nguyetminh@gemadept.com.vn  ACC       Edit    10.4. ACC
13       huypq@gemadept.com.vn  CĐS       Edit   10.14. CĐS
14     oanhpnh@gemadept.com.vn  CĐS       Edit   10.14. CĐS
15    huongbtt@gemadept.com.vn  FIN       Edit    10.3. FIN
24      bacvth@gemadept.com.vn  RM1       Edit   10.10. RM1
25      anhvtk@gemadept.com.vn  RM1       Edit   10.10. RM1
34       NgaTQ@gemadept.com.vn  RM2       Edit   10.11. RM2
35        HaNB@gemadept.com.vn  RM2       Edit   10.11. RM2
39    HuongBTT@gemadept.com.vn  R&D       Edit    10.6. R&D
40       huehl@gemadept.com.vn  R&D       Edit    10.6. R&D
48       loccq@gemadept.com.vn   IT       Edit     10.5. IT
49      cangpt@gemadept.com.vn   IT       Edit     10.5. IT
50      tuancq@gemadept.com.vn   IT       Edit     10.5. IT
51      anhttp@gemadept.com.vn   HR       Edit     10.9. HR

                                       RelativeURL
0    /sites/BSCKPI/Shared Documents/2025/10.2. ADM
3    /sites/BSCKPI/Shared Documents/2025/10.4. ACC
13  /sites/BSCKPI/Shared Documents/2025/10.14. CĐS
14  /sites/BSCKPI/Shared Documents/2025/10.14. CĐS
15   /sites/BSCKPI/Shared Documents/2025/10.3. FIN
24  /sites/BSCKPI/Shared Documents/2025/10.10. RM1
25  /sites/BSCKPI/Shared Documents/2025/10.10. RM1
34  /sites/BSCKPI/Shared Documents/2025/10.11. RM2
35  /sites/BSCKPI/Shared Documents/2025/10.11. RM2
39   /sites/BSCKPI/Shared Documents/2025/10.6. R&D
40   /sites/BSCKPI/Shared Documents/2025/10.6. R&D
48    /sites/BSCKPI/Shared Documents/2025/10.5. IT
49    /sites/BSCKPI/Shared Documents/2025/10.5. IT
50    /sites/BSCKPI/Shared Documents/2025/10.5. IT
51    /sites/BSCKPI/Shared Documents/2025/10.9. HR
Saved url_bld.xlsx

In [686]:
# PTK
ptk_df = df.dropna(subset=['PTK']).copy()
ptk_df.rename(columns={'PTK': 'Permission'}, inplace=True)

ptk_df = ptk_df[['Email', 'BU', 'Permission']]
# Optional: Print the first few rows of the new DataFrame
ptk_df.head(30)
# ptk_df.count()

                           Email       BU Permission
0       TrangTTT@gemadept.com.vn      ADM      E-all
3     nguyetminh@gemadept.com.vn      ACC      E-all
13         huypq@gemadept.com.vn      CĐS      E-all
14       oanhpnh@gemadept.com.vn      CĐS      E-all
23        binhnt@gemadept.com.vn      RM1      E-all
48         loccq@gemadept.com.vn       IT      E-all
49        cangpt@gemadept.com.vn       IT      E-all
50        tuancq@gemadept.com.vn       IT      E-all
54        binhnt@gemadept.com.vn      MKT      E-all
65          lanv@gemadept.com.vn     HSSE      E-all
88          HieuNT.GM@pip.com.vn      PME      E-all
89       hieunt.md@gmdpme.com.vn      PME      E-all
90         minhddq@gmdpme.com.vn      PME      E-all
99        dungnt@gemadept.com.vn  Khối HP      E-all
110       dungnt@gemadept.com.vn      NDV      E-all
120     giang.nn@gemadept.com.vn      NHI      E-all
121  manh.tovan@namhailog.com.vn      NHI      E-all
125       dungnt@gemadept.com.vn      GPS      E-all
133     huong.le@gemadept.com.vn      GNL      E-all
134      hung.nd@gemadept.com.vn      GNL      E-all
135       Ngocnd@gemadept.com.vn      DQP      E-all
150       LongPQ@gemadept.com.vn      GLC    E - All
155       LongPQ@gemadept.com.vn      GSC      E-all
165      khanhdc@gemadept.com.vn      GIC      E-all
171           thiennd@kgl.com.vn      KGL          V
177       LongPQ@gemadept.com.vn      MKL      E-ALL

In [687]:
# Folder RelativeURL templates
ptk_folder_url_templates = { 
    'BLD': '/sites/BSCKPI/Shared Documents/2025/{}', 
}

# Generate the RelativeURL using the BU -> Layer2 mapping
ptk_df['Layer2Folder'] = ptk_df['BU'].map(bu_to_layer2_mapping)

# Generate URL only if a valid mapping exists
ptk_df['RelativeURL'] = ptk_df['Layer2Folder'].apply(
    lambda folder: ptk_folder_url_templates['BLD'].format(folder) if folder else 'Invalid BU'
)

ptk_df['Permission'] = ptk_df['Permission'].apply(map_permission)
# Optional: Print the first few rows to verify
print(ptk_df.head(15))

# Save to Excel
filename = 'url_ptk.xlsx'
with pd.ExcelWriter(filename, engine='xlsxwriter') as writer:
    ptk_df.to_excel(writer, index=False, sheet_name="data")

    # Access the xlsxwriter workbook and sheet
    workbook = writer.book
    worksheet = writer.sheets["data"]

    # Add a table format for the data
    worksheet.add_table(0, 0, ptk_df.shape[0], ptk_df.shape[1] - 1,
                        {'columns': [{'header': col} for col in ptk_df.columns]})

    print(f'Saved {filename}')  # Optional, to confirm saving

                          Email       BU Permission Layer2Folder  \
0      TrangTTT@gemadept.com.vn      ADM       Edit    10.2. ADM
3    nguyetminh@gemadept.com.vn      ACC       Edit    10.4. ACC
13        huypq@gemadept.com.vn      CĐS       Edit   10.14. CĐS
14      oanhpnh@gemadept.com.vn      CĐS       Edit   10.14. CĐS
23       binhnt@gemadept.com.vn      RM1       Edit   10.10. RM1
48        loccq@gemadept.com.vn       IT       Edit     10.5. IT
49       cangpt@gemadept.com.vn       IT       Edit     10.5. IT
50       tuancq@gemadept.com.vn       IT       Edit     10.5. IT
54       binhnt@gemadept.com.vn      MKT       Edit    10.1. MKT
65         lanv@gemadept.com.vn     HSSE       Edit  10.13. HSSE
88         HieuNT.GM@pip.com.vn      PME       Edit     3.4. PME
89      hieunt.md@gmdpme.com.vn      PME       Edit     3.4. PME
90        minhddq@gmdpme.com.vn      PME       Edit     3.4. PME
99       dungnt@gemadept.com.vn  Khối HP       Edit   2. Khối HP
110      dungnt@gemadept.com.vn      NDV       Edit     2.1. NDV

                                         RelativeURL
0      /sites/BSCKPI/Shared Documents/2025/10.2. ADM
3      /sites/BSCKPI/Shared Documents/2025/10.4. ACC
13    /sites/BSCKPI/Shared Documents/2025/10.14. CĐS
14    /sites/BSCKPI/Shared Documents/2025/10.14. CĐS
23    /sites/BSCKPI/Shared Documents/2025/10.10. RM1
48      /sites/BSCKPI/Shared Documents/2025/10.5. IT
49      /sites/BSCKPI/Shared Documents/2025/10.5. IT
50      /sites/BSCKPI/Shared Documents/2025/10.5. IT
54     /sites/BSCKPI/Shared Documents/2025/10.1. MKT
65   /sites/BSCKPI/Shared Documents/2025/10.13. HSSE
88      /sites/BSCKPI/Shared Documents/2025/3.4. PME
89      /sites/BSCKPI/Shared Documents/2025/3.4. PME
90      /sites/BSCKPI/Shared Documents/2025/3.4. PME
99    /sites/BSCKPI/Shared Documents/2025/2. Khối HP
110     /sites/BSCKPI/Shared Documents/2025/2.1. NDV
Saved url_ptk.xlsx

In [688]:
# consolidated bld

# Combine both DataFrames
bldptk_df = pd.concat([ptk_df, bld_df], ignore_index=True)

# Remove duplicates
bldptk_df = bldptk_df.drop_duplicates()

# Optional: Reset index for cleanliness
bldptk_df.reset_index(drop=True, inplace=True)

# Display the first few rows
bldptk_df.head()
bldptk_df = bldptk_df.drop('Layer2Folder', axis=1)
bldptk_df['Permission'] = bldptk_df['Permission'].apply(map_permission)
# Save to Excel
filename = 'consolidated_url_bldptk.xlsx'
with pd.ExcelWriter(filename, engine='xlsxwriter') as writer:
    bldptk_df.to_excel(writer, index=False, sheet_name="data")

    # Access the xlsxwriter workbook and sheet
    workbook = writer.book
    worksheet = writer.sheets["data"]

    # Add a table format for the data
    worksheet.add_table(0, 0, bldptk_df.shape[0], bldptk_df.shape[1] - 1,
                        {'columns': [{'header': col} for col in bldptk_df.columns]})

    print(f'Saved {filename}')  # Optional, to confirm saving

Saved consolidated_url_bldptk.xlsx

In [689]:
# Combine all DataFrames
consolidated_doa = pd.concat([bldptk_df, pic_bsckpi_df, khprj_df_extended] + all_dfs, ignore_index=True)
consolidated_doa = consolidated_doa.drop('Layer2Folder', axis=1)

# Remove duplicates
consolidated_doa = consolidated_doa.drop_duplicates()

# Reset index for cleanliness
consolidated_doa.reset_index(drop=True, inplace=True)

# Display the first few rows
consolidated_doa.head()
consolidated_doa.count()

filename = "consolidated_doa.xlsx"

# Save to Excel with formatting
with pd.ExcelWriter(filename, engine="xlsxwriter") as writer:
    consolidated_doa.to_excel(writer, index=False, sheet_name="data")

    # Access the xlsxwriter workbook and sheet
    workbook = writer.book
    worksheet = writer.sheets["data"]

    # Add a table format for better readability
    worksheet.add_table(
        0, 0, consolidated_doa.shape[0], consolidated_doa.shape[1] - 1,
        {"columns": [{"header": col} for col in consolidated_doa.columns]}
    )

print(f"Saved {filename}")

Saved consolidated_doa.xlsx