In [1]:
print("hello")

hello

In [2]:
import pandas as pd
df=pd.read_excel("C:\\Users\\buidu\\OneDrive\\Máy tính\\thisCode\\code\\PYthon_only\\task2\\IT Operation.xlsx")
df

,Task ID,Task Name,Bucket Name,Progress,Priority,Assigned To,Created By,Created Date,Start Date,Due Date,Is Recurring,Late,Completed Date,Completed By,Completed Checklist Items,Checklist Items,Labels,Description
0,yZ7MKKmfmkW7F17FpQk7pMkAAldv,"Ticket(478), GLC HỌP THÁNG DUC THÁNG 02.2024",Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/08/2024,False,False,NaN,NaN,0/3,Ms Thắm/GLC;PH Đào tạo L21 - 9h30;H.323,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...
1,_98BmlWNSky-H-3b7cJphskAP0si,"Ticket(476), Họp review phần ngôn ngữ tiếng An...",Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/26/2024,02/26/2024,02/27/2024,False,False,NaN,NaN,NaN,NaN,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...
2,RsSYhYMSSEevknM1lziKd8kADSNi,"Ticket(475), Họp TF dự án trồng rừng",Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/01/2024,False,False,NaN,NaN,0/3,Webex;Ms Vân/R&D;PH ??? - 14h00,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...
3,DLIpJNhmqkiqfgUEt8AZtckALkzn,"Ticket(473), <pepsict>Kiểm tra email",Waitlist,In progress,Medium,NaN,Gemadept IT Helpdesk,02/25/2024,02/24/2024,02/25/2024,False,True,NaN,NaN,NaN,NaN,Red,Ghi chú:\n\n###\n* Yêu cầu bởi: GLCIT/Trinh.Ph...
4,ghL0FByfsEWVIkGqKmMwlckADD7g,"Ticket(470), [Smartport] Triển khai dịch vụ bả...",Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/23/2024,02/23/2024,02/24/2024,False,True,NaN,NaN,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: antv@cehsoft.c...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1177,LTeUWl3LvESweZF9C2RgJskALj7C,Triển khai Planner phòng ITHO,MS 365,Completed,Medium,IT/QuangHT,IT/QuangHT,08/18/2023,08/16/2023,08/17/2023,False,False,08/18/2023,IT/QuangHT,0/2,"Training ITHO;Tạo plan IT Operation, add Team ...",NaN,NaN
1178,z6MFfU4IMUa7nAICaxenCskADUvx,"Rà soát, sắp xếp lại Rack phòng Server","Network,Server/Firewall,ATTT",Completed,Medium,IT/DatTQ;IT/TuanPA,ITHO/CangPT,08/17/2023,NaN,08/18/2023,False,False,08/17/2023,IT/QuangHT,NaN,NaN,NaN,_x000D_\n_x000D_\n
1179,c0-k_AfbBESoHO_29U4WN8kABsdq,Hướng dẫn quy trình kết nối EDO cho IT PIP/BDP,SmartPort,Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,NaN,08/15/2023,False,False,08/15/2023,IT/QuangHT,0/2,Hướng dẫn tính năng sFTP;Bộ quy trình mẫu,NaN,NaN
1180,5ZMM9GC86UG8T1x9UfEFLckAN6NQ,"Hướng dẫn TTS thay đổi giao diện, cài đặt plug...","Moodle, Đào tạo, Event",Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,NaN,08/15/2023,False,False,08/15/2023,IT/QuangHT,NaN,NaN,NaN,NaN
1181,8UsYELtkfk2CDuyKjHMj6MkAJpVX,Triển khai WS Lập kế hoạch với Ms Planner,"Moodle, Đào tạo, Event",Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,08/08/2023,08/11/2023,False,False,08/15/2023,IT/QuangHT,0/4,Lập kế hoạch;Tạo slide trình chiếu;Gởi thư mời...,NaN,NaN

In [3]:
df.describe()

,Task ID,Task Name,Bucket Name,Progress,Priority,Assigned To,Created By,Created Date,Start Date,Due Date,Is Recurring,Late,Completed Date,Completed By,Completed Checklist Items,Checklist Items,Labels,Description
count,1182,1182,1182,1182,1182,1160,1182,1182,840,1157,1182,1182,1156,1156,496,496,498,932
unique,1182,923,20,3,4,40,12,138,148,166,2,2,139,12,25,424,8,567
top,yZ7MKKmfmkW7F17FpQk7pMkAAldv,Check DB system,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/07/2023,12/13/2023,08/25/2023,False,False,11/07/2023,IT/TuanPA,0/3,https://gemadeptcorp.webex.com/gemadeptcorp/j....,Light blue,_x000D_\n_x000D_\n
freq,1,90,361,1156,1124,375,503,26,18,19,1178,1172,25,427,347,25,292,299

In [4]:
df.head()

,Task ID,Task Name,Bucket Name,Progress,Priority,Assigned To,Created By,Created Date,Start Date,Due Date,Is Recurring,Late,Completed Date,Completed By,Completed Checklist Items,Checklist Items,Labels,Description
0,yZ7MKKmfmkW7F17FpQk7pMkAAldv,"Ticket(478), GLC HỌP THÁNG DUC THÁNG 02.2024",Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/08/2024,False,False,NaN,NaN,0/3,Ms Thắm/GLC;PH Đào tạo L21 - 9h30;H.323,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...
1,_98BmlWNSky-H-3b7cJphskAP0si,"Ticket(476), Họp review phần ngôn ngữ tiếng An...",Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/26/2024,02/26/2024,02/27/2024,False,False,NaN,NaN,NaN,NaN,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...
2,RsSYhYMSSEevknM1lziKd8kADSNi,"Ticket(475), Họp TF dự án trồng rừng",Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/01/2024,False,False,NaN,NaN,0/3,Webex;Ms Vân/R&D;PH ??? - 14h00,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...
3,DLIpJNhmqkiqfgUEt8AZtckALkzn,"Ticket(473), <pepsict>Kiểm tra email",Waitlist,In progress,Medium,NaN,Gemadept IT Helpdesk,02/25/2024,02/24/2024,02/25/2024,False,True,NaN,NaN,NaN,NaN,Red,Ghi chú:\n\n###\n* Yêu cầu bởi: GLCIT/Trinh.Ph...
4,ghL0FByfsEWVIkGqKmMwlckADD7g,"Ticket(470), [Smartport] Triển khai dịch vụ bả...",Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/23/2024,02/23/2024,02/24/2024,False,True,NaN,NaN,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: antv@cehsoft.c...

* replace Ticket

In [5]:
df['Task Name']=df['Task Name'].str.replace('Ticket', '')

In [6]:
df['Task Name'].head()

0               (478), GLC HỌP THÁNG DUC THÁNG 02.2024
1    (476), Họp review phần ngôn ngữ tiếng Anh trên...
2                       (475), Họp TF dự án trồng rừng
3                       (473), <pepsict>Kiểm tra email
4    (470), [Smartport] Triển khai dịch vụ bảo trì ...
Name: Task Name, dtype: object

* replace number of string type

In [7]:
df['Task Name']=df['Task Name'].replace(r'\b\d+\b', '', regex=True)

* replace '()' in dataframe

In [8]:
df['Task Name']=df['Task Name'].replace(r'\(\)', '', regex=True)

In [9]:
df['Task Name'].head()

0                          , GLC HỌP THÁNG DUC THÁNG .
1    , Họp review phần ngôn ngữ tiếng Anh trên webs...
2                            , Họp TF dự án trồng rừng
3                            , <pepsict>Kiểm tra email
4    , [Smartport] Triển khai dịch vụ bảo trì SMP v...
Name: Task Name, dtype: object

* replace firt comma in dataframe

In [10]:
df['Task Name'].replace(r'^([^,]*),', r'\1', regex=True)

0                               GLC HỌP THÁNG DUC THÁNG .
1        Họp review phần ngôn ngữ tiếng Anh trên websi...
2                                 Họp TF dự án trồng rừng
3                                 <pepsict>Kiểm tra email
4        [Smartport] Triển khai dịch vụ bảo trì SMP và...
                              ...
1177                        Triển khai Planner phòng ITHO
1178                Rà soát sắp xếp lại Rack phòng Server
1179       Hướng dẫn quy trình kết nối EDO cho IT PIP/BDP
1180    Hướng dẫn TTS thay đổi giao diện cài đặt plugi...
1181            Triển khai WS Lập kế hoạch với Ms Planner
Name: Task Name, Length: 1182, dtype: object

In [11]:
df['Task Name'].head()

0                          , GLC HỌP THÁNG DUC THÁNG .
1    , Họp review phần ngôn ngữ tiếng Anh trên webs...
2                            , Họp TF dự án trồng rừng
3                            , <pepsict>Kiểm tra email
4    , [Smartport] Triển khai dịch vụ bảo trì SMP v...
Name: Task Name, dtype: object

In [12]:
df.head()

,Task ID,Task Name,Bucket Name,Progress,Priority,Assigned To,Created By,Created Date,Start Date,Due Date,Is Recurring,Late,Completed Date,Completed By,Completed Checklist Items,Checklist Items,Labels,Description
0,yZ7MKKmfmkW7F17FpQk7pMkAAldv,", GLC HỌP THÁNG DUC THÁNG .",Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/08/2024,False,False,NaN,NaN,0/3,Ms Thắm/GLC;PH Đào tạo L21 - 9h30;H.323,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...
1,_98BmlWNSky-H-3b7cJphskAP0si,", Họp review phần ngôn ngữ tiếng Anh trên webs...",Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/26/2024,02/26/2024,02/27/2024,False,False,NaN,NaN,NaN,NaN,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...
2,RsSYhYMSSEevknM1lziKd8kADSNi,", Họp TF dự án trồng rừng",Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/01/2024,False,False,NaN,NaN,0/3,Webex;Ms Vân/R&D;PH ??? - 14h00,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...
3,DLIpJNhmqkiqfgUEt8AZtckALkzn,", <pepsict>Kiểm tra email",Waitlist,In progress,Medium,NaN,Gemadept IT Helpdesk,02/25/2024,02/24/2024,02/25/2024,False,True,NaN,NaN,NaN,NaN,Red,Ghi chú:\n\n###\n* Yêu cầu bởi: GLCIT/Trinh.Ph...
4,ghL0FByfsEWVIkGqKmMwlckADD7g,", [Smartport] Triển khai dịch vụ bảo trì SMP v...",Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/23/2024,02/23/2024,02/24/2024,False,True,NaN,NaN,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: antv@cehsoft.c...

In [13]:
df[571:585]

,Task ID,Task Name,Bucket Name,Progress,Priority,Assigned To,Created By,Created Date,Start Date,Due Date,Is Recurring,Late,Completed Date,Completed By,Completed Checklist Items,Checklist Items,Labels,Description
571,3T5iOeLCa0mLW2OTHFl4CskACvQ3,"(032c14), [GSC] HỌP MKT COC - /",Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/17/2023,False,False,11/17/2023,IT/TuanPA,0/3,PH lầu 20 - 9h00;Ms Dung/GSC.ADM;Webex,Light blue,_x000D_\nGhi chú: _x000D_\n _x000D_\n### _x...
572,IWbbRiG-ZUiMctRSO8S8W8kABFY-,"(baf0ed), Họp về SP1.4_Báo cáo dự báo SL DT củ...",Ticket,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/16/2023,11/16/2023,11/17/2023,False,False,11/17/2023,IT/TuanPA,NaN,NaN,NaN,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...
573,0KQhEg8rW0qHQMizsmqCTckAOjSz,"(3b624d), FW: THANH LÝ NGHỈ VIỆC",Ticket,Completed,Medium,IT/NhutNDQ,Gemadept IT Helpdesk,11/16/2023,11/16/2023,11/17/2023,False,False,11/17/2023,IT/NhutNDQ,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: IT/NhutNDQ\n* ...
574,I4VuEQ6wM0-ynOXGAEbcAMkAEtMp,"(d8b22f), HỌP PHỐI HỢP GSC - PIP",Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Webex;PH Đào tạo L21 - 16h00;Mr Tuấn/GSC.OPS,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...
575,myYnT3Z4Hk2x-C6AlSfOeskAKKeC,"(ebcce1), Anh Long họp BCH",Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Webex;PH lầu 21 - 15h00;Ms Thư/ADM,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...
576,6A2hwHIHEE2OV3Q5s3MMmMkAPVBl,"(6755e7), GMD ACC Meeting",Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Mr Sơn/ACC;PH lầu 18 - 14h00;Webex,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...
577,5V-vkzjRVEWA2STDwtUZEckAL6o-,"(556a99), Họp MKT-BD Tháng /",Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Ms Lan/MKT HO;Webex;PH Đào tạo L21 - 13h45,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...
578,ANoExwT5I0i1RxfcrJsruskAO7P8,"(56b6ea), Họp triển khai PRJ MKT-BD",Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Webex;PH Đào tạo L21 - 8h30;Ms Lan/MKT HO,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...
579,SA1Blyfr202IgJv_dkLSgskAJPx9,"(3f215c), Ổ đĩa C báo đầy (Ms Loan/RM2)",Ticket,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/16/2023,11/16/2023,11/17/2023,False,False,11/16/2023,IT/TuanPA,NaN,NaN,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...
580,bjTmOm1k_k-F8pfth_WUf8kALRb1,Hướng dẫn Cập nhật Flow tạo task nội bộ,MS 365,Completed,Medium,IT/QuangHT,IT/QuangHT,11/15/2023,NaN,11/16/2023,False,False,11/16/2023,IT/QuangHT,NaN,NaN,NaN,_x000D_\n_x000D_\n
581,WL6avO-H60-KXHYty1PWsckAFE9B,Hướng dẫn fix lỗi webserver GSC,"GSC, JJS",Completed,Medium,IT/QuangHT,IT/QuangHT,11/15/2023,NaN,11/15/2023,False,False,11/15/2023,IT/QuangHT,0/2,"Remove App redirect lạ, remove code redirect t...",NaN,"_x000D_\nLỗi website redirect, restart site nà..."
582,j8pQ8TdUNUyFtEl6uhJvJskAMaDo,"TID: ff7c36, Họp ban Projection Tập Đoàn và Ge...",Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/13/2023,11/15/2023,11/15/2023,False,False,11/15/2023,IT/TuanPA,0/3,Webex;Mr An/XDHT;PH Đào tạo L21 - 14h00,Light blue,_x000D_\n* Yêu cầu bởi: IT/TuanPA _x000D_\n_x...
583,pddz1SYqSEeeYL8fX9EC8MkAOdR8,"(b37781), GSC- Projection Meeting",Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/14/2023,11/15/2023,11/15/2023,False,False,11/15/2023,IT/TuanPA,0/3,Webex;PH Đào tạo L21 - 10h00;Ms Hoài Anh/GSC,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...
584,jBRl031jHkOba265c30ML8kAPAY5,"(03fca4), HỌP - MLOS - OPS- CAM/ sáng thứ ngà...",Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/14/2023,11/15/2023,11/15/2023,False,False,11/15/2023,IT/TuanPA,0/3,Ms Trúc/GSC;PH lầu 20 - 8h30;Webex,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...

In [14]:
df.head()

,Task ID,Task Name,Bucket Name,Progress,Priority,Assigned To,Created By,Created Date,Start Date,Due Date,Is Recurring,Late,Completed Date,Completed By,Completed Checklist Items,Checklist Items,Labels,Description
0,yZ7MKKmfmkW7F17FpQk7pMkAAldv,", GLC HỌP THÁNG DUC THÁNG .",Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/08/2024,False,False,NaN,NaN,0/3,Ms Thắm/GLC;PH Đào tạo L21 - 9h30;H.323,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...
1,_98BmlWNSky-H-3b7cJphskAP0si,", Họp review phần ngôn ngữ tiếng Anh trên webs...",Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/26/2024,02/26/2024,02/27/2024,False,False,NaN,NaN,NaN,NaN,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...
2,RsSYhYMSSEevknM1lziKd8kADSNi,", Họp TF dự án trồng rừng",Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/01/2024,False,False,NaN,NaN,0/3,Webex;Ms Vân/R&D;PH ??? - 14h00,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...
3,DLIpJNhmqkiqfgUEt8AZtckALkzn,", <pepsict>Kiểm tra email",Waitlist,In progress,Medium,NaN,Gemadept IT Helpdesk,02/25/2024,02/24/2024,02/25/2024,False,True,NaN,NaN,NaN,NaN,Red,Ghi chú:\n\n###\n* Yêu cầu bởi: GLCIT/Trinh.Ph...
4,ghL0FByfsEWVIkGqKmMwlckADD7g,", [Smartport] Triển khai dịch vụ bảo trì SMP v...",Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/23/2024,02/23/2024,02/24/2024,False,True,NaN,NaN,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: antv@cehsoft.c...

In [57]:
def split_name(name):
    return pd.Series(name.split(",", 1))
df[['First Name', 'Last Name']] = df['Task Name'].apply(split_name)

In [58]:
df

,Task ID,Task Name,Bucket Name,Progress,Priority,Assigned To,Created By,Created Date,Start Date,Due Date,Is Recurring,Late,Completed Date,Completed By,Completed Checklist Items,Checklist Items,Labels,Description,First Name,Last Name
0,yZ7MKKmfmkW7F17FpQk7pMkAAldv,", GLC HỌP THÁNG DUC THÁNG .",Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/08/2024,False,False,NaN,NaN,0/3,Ms Thắm/GLC;PH Đào tạo L21 - 9h30;H.323,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...,,GLC HỌP THÁNG DUC THÁNG .
1,_98BmlWNSky-H-3b7cJphskAP0si,", Họp review phần ngôn ngữ tiếng Anh trên webs...",Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/26/2024,02/26/2024,02/27/2024,False,False,NaN,NaN,NaN,NaN,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...,,Họp review phần ngôn ngữ tiếng Anh trên websi...
2,RsSYhYMSSEevknM1lziKd8kADSNi,", Họp TF dự án trồng rừng",Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/01/2024,False,False,NaN,NaN,0/3,Webex;Ms Vân/R&D;PH ??? - 14h00,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...,,Họp TF dự án trồng rừng
3,DLIpJNhmqkiqfgUEt8AZtckALkzn,", <pepsict>Kiểm tra email",Waitlist,In progress,Medium,NaN,Gemadept IT Helpdesk,02/25/2024,02/24/2024,02/25/2024,False,True,NaN,NaN,NaN,NaN,Red,Ghi chú:\n\n###\n* Yêu cầu bởi: GLCIT/Trinh.Ph...,,<pepsict>Kiểm tra email
4,ghL0FByfsEWVIkGqKmMwlckADD7g,", [Smartport] Triển khai dịch vụ bảo trì SMP v...",Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/23/2024,02/23/2024,02/24/2024,False,True,NaN,NaN,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: antv@cehsoft.c...,,[Smartport] Triển khai dịch vụ bảo trì SMP và...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1177,LTeUWl3LvESweZF9C2RgJskALj7C,Triển khai Planner phòng ITHO,MS 365,Completed,Medium,IT/QuangHT,IT/QuangHT,08/18/2023,08/16/2023,08/17/2023,False,False,08/18/2023,IT/QuangHT,0/2,"Training ITHO;Tạo plan IT Operation, add Team ...",NaN,NaN,Triển khai Planner phòng ITHO,NaN
1178,z6MFfU4IMUa7nAICaxenCskADUvx,"Rà soát, sắp xếp lại Rack phòng Server","Network,Server/Firewall,ATTT",Completed,Medium,IT/DatTQ;IT/TuanPA,ITHO/CangPT,08/17/2023,NaN,08/18/2023,False,False,08/17/2023,IT/QuangHT,NaN,NaN,NaN,_x000D_\n_x000D_\n,Rà soát,sắp xếp lại Rack phòng Server
1179,c0-k_AfbBESoHO_29U4WN8kABsdq,Hướng dẫn quy trình kết nối EDO cho IT PIP/BDP,SmartPort,Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,NaN,08/15/2023,False,False,08/15/2023,IT/QuangHT,0/2,Hướng dẫn tính năng sFTP;Bộ quy trình mẫu,NaN,NaN,Hướng dẫn quy trình kết nối EDO cho IT PIP/BDP,NaN
1180,5ZMM9GC86UG8T1x9UfEFLckAN6NQ,"Hướng dẫn TTS thay đổi giao diện, cài đặt plug...","Moodle, Đào tạo, Event",Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,NaN,08/15/2023,False,False,08/15/2023,IT/QuangHT,NaN,NaN,NaN,NaN,Hướng dẫn TTS thay đổi giao diện,cài đặt plugins mới
1181,8UsYELtkfk2CDuyKjHMj6MkAJpVX,Triển khai WS Lập kế hoạch với Ms Planner,"Moodle, Đào tạo, Event",Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,08/08/2023,08/11/2023,False,False,08/15/2023,IT/QuangHT,0/4,Lập kế hoạch;Tạo slide trình chiếu;Gởi thư mời...,NaN,NaN,Triển khai WS Lập kế hoạch với Ms Planner,NaN

In [59]:


df = df.drop('Task Name', axis=1)

In [60]:
df

,Task ID,Bucket Name,Progress,Priority,Assigned To,Created By,Created Date,Start Date,Due Date,Is Recurring,Late,Completed Date,Completed By,Completed Checklist Items,Checklist Items,Labels,Description,First Name,Last Name
0,yZ7MKKmfmkW7F17FpQk7pMkAAldv,Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/08/2024,False,False,NaN,NaN,0/3,Ms Thắm/GLC;PH Đào tạo L21 - 9h30;H.323,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...,,GLC HỌP THÁNG DUC THÁNG .
1,_98BmlWNSky-H-3b7cJphskAP0si,Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/26/2024,02/26/2024,02/27/2024,False,False,NaN,NaN,NaN,NaN,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...,,Họp review phần ngôn ngữ tiếng Anh trên websi...
2,RsSYhYMSSEevknM1lziKd8kADSNi,Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/01/2024,False,False,NaN,NaN,0/3,Webex;Ms Vân/R&D;PH ??? - 14h00,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...,,Họp TF dự án trồng rừng
3,DLIpJNhmqkiqfgUEt8AZtckALkzn,Waitlist,In progress,Medium,NaN,Gemadept IT Helpdesk,02/25/2024,02/24/2024,02/25/2024,False,True,NaN,NaN,NaN,NaN,Red,Ghi chú:\n\n###\n* Yêu cầu bởi: GLCIT/Trinh.Ph...,,<pepsict>Kiểm tra email
4,ghL0FByfsEWVIkGqKmMwlckADD7g,Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/23/2024,02/23/2024,02/24/2024,False,True,NaN,NaN,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: antv@cehsoft.c...,,[Smartport] Triển khai dịch vụ bảo trì SMP và...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1177,LTeUWl3LvESweZF9C2RgJskALj7C,MS 365,Completed,Medium,IT/QuangHT,IT/QuangHT,08/18/2023,08/16/2023,08/17/2023,False,False,08/18/2023,IT/QuangHT,0/2,"Training ITHO;Tạo plan IT Operation, add Team ...",NaN,NaN,Triển khai Planner phòng ITHO,NaN
1178,z6MFfU4IMUa7nAICaxenCskADUvx,"Network,Server/Firewall,ATTT",Completed,Medium,IT/DatTQ;IT/TuanPA,ITHO/CangPT,08/17/2023,NaN,08/18/2023,False,False,08/17/2023,IT/QuangHT,NaN,NaN,NaN,_x000D_\n_x000D_\n,Rà soát,sắp xếp lại Rack phòng Server
1179,c0-k_AfbBESoHO_29U4WN8kABsdq,SmartPort,Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,NaN,08/15/2023,False,False,08/15/2023,IT/QuangHT,0/2,Hướng dẫn tính năng sFTP;Bộ quy trình mẫu,NaN,NaN,Hướng dẫn quy trình kết nối EDO cho IT PIP/BDP,NaN
1180,5ZMM9GC86UG8T1x9UfEFLckAN6NQ,"Moodle, Đào tạo, Event",Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,NaN,08/15/2023,False,False,08/15/2023,IT/QuangHT,NaN,NaN,NaN,NaN,Hướng dẫn TTS thay đổi giao diện,cài đặt plugins mới
1181,8UsYELtkfk2CDuyKjHMj6MkAJpVX,"Moodle, Đào tạo, Event",Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,08/08/2023,08/11/2023,False,False,08/15/2023,IT/QuangHT,0/4,Lập kế hoạch;Tạo slide trình chiếu;Gởi thư mời...,NaN,NaN,Triển khai WS Lập kế hoạch với Ms Planner,NaN

In [61]:
df[555:585]

,Task ID,Bucket Name,Progress,Priority,Assigned To,Created By,Created Date,Start Date,Due Date,Is Recurring,Late,Completed Date,Completed By,Completed Checklist Items,Checklist Items,Labels,Description,First Name,Last Name
555,Z3kIUWX5RkiA8yXjbA3QkMkAAkJl,"PC, Workstation, Helpdesk",Completed,Medium,IT/TuanPA,IT/TuanPA,11/20/2023,11/20/2023,11/20/2023,False,False,11/20/2023,IT/TuanPA,1/2,"Thay acquy mới, dán nhãn ngày thay để thao dõi...",NaN,_x000D_\n_x000D_\n,Thay acquy UPS 500VA (Mr Tuấn/ACC),NaN
556,iWyebC3b_0qmRH_rJA2Fa8kAMFLj,"WebPortal, Website",Completed,Medium,IT/QuangHT,Gemadept IT Helpdesk,11/20/2023,11/20/2023,11/21/2023,False,False,11/20/2023,IT/QuangHT,NaN,NaN,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...,(6215db),Thống kê truy cập Bản tin Logistics
557,FhMeQSsLtUGYM0aze8C5BMkAFM1r,Ticket,Completed,Medium,IT/NhutNDQ,Gemadept IT Helpdesk,11/20/2023,11/20/2023,11/21/2023,False,False,11/20/2023,IT/NhutNDQ,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: IT/NhutNDQ\n* ...,(fc63da),Tao mail Gemadept
558,0F5RcaNoQUq_kMWrgZeHdMkAAnnV,Ticket,Completed,Medium,IT/NhutNDQ,Gemadept IT Helpdesk,11/20/2023,11/20/2023,11/21/2023,False,False,11/20/2023,IT/NhutNDQ,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: IT/NhutNDQ\n* ...,(a8c50e),Báo cáo dự án ATTT tập đoàn
559,5FMairfQvUGg3iInVHxZC8kALZJm,Meeting Support,Completed,Important,IT/ThaiTD;IT/TuanPA,IT/TuanPA,11/13/2023,11/13/2023,11/20/2023,False,False,11/20/2023,IT/TuanPA,0/3,https://gemadeptcorp.webex.com/gemadeptcorp/j....,NaN,_x000D_\nHỌP GIAO BAN TUẦN CỦA GSC LÚC 10H SÁN...,HỌP GIAO BAN TUẦN GSC (GSC WEEKLY MEETING),NaN
560,wyH_QLLje0i0mZfMv7ufy8kAM-Ks,SmartPort,Completed,Medium,IT/NhutNDQ;IT/TuanCQ;IT/QuangHT;ITHO/CangPT,Gemadept IT Helpdesk,11/13/2023,11/14/2023,11/17/2023,False,False,11/20/2023,IT/NhutNDQ,0/4,"Tạo folder BackupSMP, share có mật khẩu, gửi t...",Light blue,_x000D_\n* Yêu cầu bởi: IT/QuangHT _x000D_\n_...,(11d175),Triển khai backup dữ liệu Smartport về hệ thố...
561,bfUOiFKaW0ucJEGGlaf22MkAGJVM,"Oracle, E-Invoice",Completed,Medium,IT/TuanCQ,IT/TuanCQ,11/20/2023,NaN,11/15/2023,False,False,11/20/2023,IT/TuanCQ,NaN,NaN,NaN,_x000D_\n_x000D_\n,Check DB system,NaN
562,KTvJhkmCV0aAc9ydjCcd2skAL7Oh,"Oracle, E-Invoice",Completed,Medium,IT/TuanCQ,IT/TuanCQ,11/20/2023,NaN,11/15/2023,False,False,11/20/2023,IT/TuanCQ,NaN,NaN,NaN,NaN,Check Backup System,NaN
563,6zCcziGPrkeZ7b8wT7JJ2skAHUZk,"Oracle, E-Invoice",Completed,Medium,IT/TuanCQ,IT/TuanCQ,11/20/2023,NaN,11/14/2023,False,False,11/20/2023,IT/TuanCQ,NaN,NaN,NaN,_x000D_\n_x000D_\n,Check DB system,NaN
564,D-GD_A3k5kGGsE6RsVZSNckAJtYi,"Oracle, E-Invoice",Completed,Medium,IT/TuanCQ,IT/TuanCQ,11/20/2023,NaN,11/14/2023,False,False,11/20/2023,IT/TuanCQ,NaN,NaN,NaN,NaN,Check Backup System,NaN
565,X3GTI7s8kkOUosRL4iEcuckACWkT,"Oracle, E-Invoice",Completed,Medium,IT/TuanCQ,IT/TuanCQ,11/10/2023,NaN,11/13/2023,False,False,11/20/2023,IT/TuanCQ,NaN,NaN,NaN,NaN,Check Backup System,NaN
566,saZ_mcIy7UOJtiistc2yKskAAnbk,"Oracle, E-Invoice",Completed,Medium,IT/TuanCQ,IT/TuanCQ,11/10/2023,NaN,11/13/2023,False,False,11/20/2023,IT/TuanCQ,NaN,NaN,NaN,_x000D_\n_x000D_\n,Check DB system,NaN
567,NaGYiRWGDk-xZQ-MZTVtCskAKIz3,Ticket,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/17/2023,11/17/2023,11/18/2023,False,False,11/17/2023,IT/TuanPA,NaN,NaN,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...,(95608e),RE: MKT-BD - Chia sẻ thẻ L (Ms Hoa)
568,nPtfGBpfJUGiWFcjzAsrHskAHo2K,Ticket,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/16/2023,11/16/2023,11/17/2023,False,False,11/17/2023,IT/TuanPA,0/1,13h30 chuẩn bị bộ Microphone lầu 23 cho tập Vă...,Light blue,_x000D_\n _x000D_\n_x000D_\n,(63f676),TỔNG DUYỆT VÀ BIỂU DIỄN VĂN NGHỆ HN TRI ÂN KH...
569,GzLr6BXJyUazaQ50r69kFskAKxv_,MS 365,Completed,Medium,IT/QuangHT,Gemadept IT Helpdesk,11/16/2023,11/16/2023,11/17/2023,False,False,11/17/2023,IT/QuangHT,NaN,NaN,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...,(66ab7f),Hướng dẫn cài đặt tính năng tạo task nội bộ c...
570,6WSCO4G2IUOumLNGrbBS88kAMhtT,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/10/2023,11/11/2023,11/17/2023,False,False,11/17/2023,IT/TuanPA,0/3,Webex;PH lầu 21 -8h30;Ms Lan/MKT HO,Light blue,_x000D_\n* Yêu cầu bởi: IT/TuanPA _x000D_\n_x...,TID: 1b38a1,MKT-BD Họp ĐVTV về biểu mẫu SP1. (Báo cáo dự ...
571,3T5iOeLCa0mLW2OTHFl4CskACvQ3,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/17/2023,False,False,11/17/2023,IT/TuanPA,0/3,PH lầu 20 - 9h00;Ms Dung/GSC.ADM;Webex,Light blue,_x000D_\nGhi chú: _x000D_\n _x000D_\n### _x...,(032c14),[GSC] HỌP MKT COC - /
572,IWbbRiG-ZUiMctRSO8S8W8kABFY-,Ticket,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/16/2023,11/16/2023,11/17/2023,False,False,11/17/2023,IT/TuanPA,NaN,NaN,NaN,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...,(baf0ed),Họp về SP1.4_Báo cáo dự báo SL DT của các Đơn...
573,0KQhEg8rW0qHQMizsmqCTckAOjSz,Ticket,Completed,Medium,IT/NhutNDQ,Gemadept IT Helpdesk,11/16/2023,11/16/2023,11/17/2023,False,False,11/17/2023,IT/NhutNDQ,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: IT/NhutNDQ\n* ...,(3b624d),FW: THANH LÝ NGHỈ VIỆC
574,I4VuEQ6wM0-ynOXGAEbcAMkAEtMp,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Webex;PH Đào tạo L21 - 16h00;Mr Tuấn/GSC.OPS,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...,(d8b22f),HỌP PHỐI HỢP GSC - PIP
575,myYnT3Z4Hk2x-C6AlSfOeskAKKeC,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Webex;PH lầu 21 - 15h00;Ms Thư/ADM,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...,(ebcce1),Anh Long họp BCH
576,6A2hwHIHEE2OV3Q5s3MMmMkAPVBl,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Mr Sơn/ACC;PH lầu 18 - 14h00;Webex,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...,(6755e7),GMD ACC Meeting
577,5V-vkzjRVEWA2STDwtUZEckAL6o-,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Ms Lan/MKT HO;Webex;PH Đào tạo L21 - 13h45,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...,(556a99),Họp MKT-BD Tháng /
578,ANoExwT5I0i1RxfcrJsruskAO7P8,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Webex;PH Đào tạo L21 - 8h30;Ms Lan/MKT HO,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...,(56b6ea),Họp triển khai PRJ MKT-BD
579,SA1Blyfr202IgJv_dkLSgskAJPx9,Ticket,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/16/2023,11/16/2023,11/17/2023,False,False,11/16/2023,IT/TuanPA,NaN,NaN,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...,(3f215c),Ổ đĩa C báo đầy (Ms Loan/RM2)
580,bjTmOm1k_k-F8pfth_WUf8kALRb1,MS 365,Completed,Medium,IT/QuangHT,IT/QuangHT,11/15/2023,NaN,11/16/2023,False,False,11/16/2023,IT/QuangHT,NaN,NaN,NaN,_x000D_\n_x000D_\n,Hướng dẫn Cập nhật Flow tạo task nội bộ,NaN
581,WL6avO-H60-KXHYty1PWsckAFE9B,"GSC, JJS",Completed,Medium,IT/QuangHT,IT/QuangHT,11/15/2023,NaN,11/15/2023,False,False,11/15/2023,IT/QuangHT,0/2,"Remove App redirect lạ, remove code redirect t...",NaN,"_x000D_\nLỗi website redirect, restart site nà...",Hướng dẫn fix lỗi webserver GSC,NaN
582,j8pQ8TdUNUyFtEl6uhJvJskAMaDo,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/13/2023,11/15/2023,11/15/2023,False,False,11/15/2023,IT/TuanPA,0/3,Webex;Mr An/XDHT;PH Đào tạo L21 - 14h00,Light blue,_x000D_\n* Yêu cầu bởi: IT/TuanPA _x000D_\n_x...,TID: ff7c36,Họp ban Projection Tập Đoàn và Gemalink
583,pddz1SYqSEeeYL8fX9EC8MkAOdR8,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/14/2023,11/15/2023,11/15/2023,False,False,11/15/2023,IT/TuanPA,0/3,Webex;PH Đào tạo L21 - 10h00;Ms Hoài Anh/GSC,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...,(b37781),GSC- Projection Meeting
584,jBRl031jHkOba265c30ML8kAPAY5,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/14/2023,11/15/2023,11/15/2023,False,False,11/15/2023,IT/TuanPA,0/3,Ms Trúc/GSC;PH lầu 20 - 8h30;Webex,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...,(03fca4),HỌP - MLOS - OPS- CAM/ sáng thứ ngày //

In [75]:
df['First Name']=df['First Name'].replace(r'\(\)', '', regex=True)

In [78]:
df['First Name'] = df['First Name'].str.replace(r'\(.*\)', '', regex=True)

In [79]:
df[555:585]

,Task ID,Bucket Name,Progress,Priority,Assigned To,Created By,Created Date,Start Date,Due Date,Is Recurring,Late,Completed Date,Completed By,Completed Checklist Items,Checklist Items,Labels,Description,First Name,Last Name
555,Z3kIUWX5RkiA8yXjbA3QkMkAAkJl,"PC, Workstation, Helpdesk",Completed,Medium,IT/TuanPA,IT/TuanPA,11/20/2023,11/20/2023,11/20/2023,False,False,11/20/2023,IT/TuanPA,1/2,"Thay acquy mới, dán nhãn ngày thay để thao dõi...",NaN,_x000D_\n_x000D_\n,Thay acquy UPS 500VA,NaN
556,iWyebC3b_0qmRH_rJA2Fa8kAMFLj,"WebPortal, Website",Completed,Medium,IT/QuangHT,Gemadept IT Helpdesk,11/20/2023,11/20/2023,11/21/2023,False,False,11/20/2023,IT/QuangHT,NaN,NaN,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...,,Thống kê truy cập Bản tin Logistics
557,FhMeQSsLtUGYM0aze8C5BMkAFM1r,Ticket,Completed,Medium,IT/NhutNDQ,Gemadept IT Helpdesk,11/20/2023,11/20/2023,11/21/2023,False,False,11/20/2023,IT/NhutNDQ,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: IT/NhutNDQ\n* ...,,Tao mail Gemadept
558,0F5RcaNoQUq_kMWrgZeHdMkAAnnV,Ticket,Completed,Medium,IT/NhutNDQ,Gemadept IT Helpdesk,11/20/2023,11/20/2023,11/21/2023,False,False,11/20/2023,IT/NhutNDQ,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: IT/NhutNDQ\n* ...,,Báo cáo dự án ATTT tập đoàn
559,5FMairfQvUGg3iInVHxZC8kALZJm,Meeting Support,Completed,Important,IT/ThaiTD;IT/TuanPA,IT/TuanPA,11/13/2023,11/13/2023,11/20/2023,False,False,11/20/2023,IT/TuanPA,0/3,https://gemadeptcorp.webex.com/gemadeptcorp/j....,NaN,_x000D_\nHỌP GIAO BAN TUẦN CỦA GSC LÚC 10H SÁN...,HỌP GIAO BAN TUẦN GSC,NaN
560,wyH_QLLje0i0mZfMv7ufy8kAM-Ks,SmartPort,Completed,Medium,IT/NhutNDQ;IT/TuanCQ;IT/QuangHT;ITHO/CangPT,Gemadept IT Helpdesk,11/13/2023,11/14/2023,11/17/2023,False,False,11/20/2023,IT/NhutNDQ,0/4,"Tạo folder BackupSMP, share có mật khẩu, gửi t...",Light blue,_x000D_\n* Yêu cầu bởi: IT/QuangHT _x000D_\n_...,,Triển khai backup dữ liệu Smartport về hệ thố...
561,bfUOiFKaW0ucJEGGlaf22MkAGJVM,"Oracle, E-Invoice",Completed,Medium,IT/TuanCQ,IT/TuanCQ,11/20/2023,NaN,11/15/2023,False,False,11/20/2023,IT/TuanCQ,NaN,NaN,NaN,_x000D_\n_x000D_\n,Check DB system,NaN
562,KTvJhkmCV0aAc9ydjCcd2skAL7Oh,"Oracle, E-Invoice",Completed,Medium,IT/TuanCQ,IT/TuanCQ,11/20/2023,NaN,11/15/2023,False,False,11/20/2023,IT/TuanCQ,NaN,NaN,NaN,NaN,Check Backup System,NaN
563,6zCcziGPrkeZ7b8wT7JJ2skAHUZk,"Oracle, E-Invoice",Completed,Medium,IT/TuanCQ,IT/TuanCQ,11/20/2023,NaN,11/14/2023,False,False,11/20/2023,IT/TuanCQ,NaN,NaN,NaN,_x000D_\n_x000D_\n,Check DB system,NaN
564,D-GD_A3k5kGGsE6RsVZSNckAJtYi,"Oracle, E-Invoice",Completed,Medium,IT/TuanCQ,IT/TuanCQ,11/20/2023,NaN,11/14/2023,False,False,11/20/2023,IT/TuanCQ,NaN,NaN,NaN,NaN,Check Backup System,NaN
565,X3GTI7s8kkOUosRL4iEcuckACWkT,"Oracle, E-Invoice",Completed,Medium,IT/TuanCQ,IT/TuanCQ,11/10/2023,NaN,11/13/2023,False,False,11/20/2023,IT/TuanCQ,NaN,NaN,NaN,NaN,Check Backup System,NaN
566,saZ_mcIy7UOJtiistc2yKskAAnbk,"Oracle, E-Invoice",Completed,Medium,IT/TuanCQ,IT/TuanCQ,11/10/2023,NaN,11/13/2023,False,False,11/20/2023,IT/TuanCQ,NaN,NaN,NaN,_x000D_\n_x000D_\n,Check DB system,NaN
567,NaGYiRWGDk-xZQ-MZTVtCskAKIz3,Ticket,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/17/2023,11/17/2023,11/18/2023,False,False,11/17/2023,IT/TuanPA,NaN,NaN,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...,,RE: MKT-BD - Chia sẻ thẻ L (Ms Hoa)
568,nPtfGBpfJUGiWFcjzAsrHskAHo2K,Ticket,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/16/2023,11/16/2023,11/17/2023,False,False,11/17/2023,IT/TuanPA,0/1,13h30 chuẩn bị bộ Microphone lầu 23 cho tập Vă...,Light blue,_x000D_\n _x000D_\n_x000D_\n,,TỔNG DUYỆT VÀ BIỂU DIỄN VĂN NGHỆ HN TRI ÂN KH...
569,GzLr6BXJyUazaQ50r69kFskAKxv_,MS 365,Completed,Medium,IT/QuangHT,Gemadept IT Helpdesk,11/16/2023,11/16/2023,11/17/2023,False,False,11/17/2023,IT/QuangHT,NaN,NaN,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...,,Hướng dẫn cài đặt tính năng tạo task nội bộ c...
570,6WSCO4G2IUOumLNGrbBS88kAMhtT,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/10/2023,11/11/2023,11/17/2023,False,False,11/17/2023,IT/TuanPA,0/3,Webex;PH lầu 21 -8h30;Ms Lan/MKT HO,Light blue,_x000D_\n* Yêu cầu bởi: IT/TuanPA _x000D_\n_x...,TID: 1b38a1,MKT-BD Họp ĐVTV về biểu mẫu SP1. (Báo cáo dự ...
571,3T5iOeLCa0mLW2OTHFl4CskACvQ3,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/17/2023,False,False,11/17/2023,IT/TuanPA,0/3,PH lầu 20 - 9h00;Ms Dung/GSC.ADM;Webex,Light blue,_x000D_\nGhi chú: _x000D_\n _x000D_\n### _x...,,[GSC] HỌP MKT COC - /
572,IWbbRiG-ZUiMctRSO8S8W8kABFY-,Ticket,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/16/2023,11/16/2023,11/17/2023,False,False,11/17/2023,IT/TuanPA,NaN,NaN,NaN,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...,,Họp về SP1.4_Báo cáo dự báo SL DT của các Đơn...
573,0KQhEg8rW0qHQMizsmqCTckAOjSz,Ticket,Completed,Medium,IT/NhutNDQ,Gemadept IT Helpdesk,11/16/2023,11/16/2023,11/17/2023,False,False,11/17/2023,IT/NhutNDQ,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: IT/NhutNDQ\n* ...,,FW: THANH LÝ NGHỈ VIỆC
574,I4VuEQ6wM0-ynOXGAEbcAMkAEtMp,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Webex;PH Đào tạo L21 - 16h00;Mr Tuấn/GSC.OPS,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...,,HỌP PHỐI HỢP GSC - PIP
575,myYnT3Z4Hk2x-C6AlSfOeskAKKeC,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Webex;PH lầu 21 - 15h00;Ms Thư/ADM,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...,,Anh Long họp BCH
576,6A2hwHIHEE2OV3Q5s3MMmMkAPVBl,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Mr Sơn/ACC;PH lầu 18 - 14h00;Webex,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...,,GMD ACC Meeting
577,5V-vkzjRVEWA2STDwtUZEckAL6o-,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Ms Lan/MKT HO;Webex;PH Đào tạo L21 - 13h45,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...,,Họp MKT-BD Tháng /
578,ANoExwT5I0i1RxfcrJsruskAO7P8,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/15/2023,11/15/2023,11/16/2023,False,False,11/16/2023,IT/TuanPA,0/3,Webex;PH Đào tạo L21 - 8h30;Ms Lan/MKT HO,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...,,Họp triển khai PRJ MKT-BD
579,SA1Blyfr202IgJv_dkLSgskAJPx9,Ticket,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/16/2023,11/16/2023,11/17/2023,False,False,11/16/2023,IT/TuanPA,NaN,NaN,Light blue,_x000D_\nGhi chú: _x000D_\n_x000D_\n_x000D_\n...,,Ổ đĩa C báo đầy (Ms Loan/RM2)
580,bjTmOm1k_k-F8pfth_WUf8kALRb1,MS 365,Completed,Medium,IT/QuangHT,IT/QuangHT,11/15/2023,NaN,11/16/2023,False,False,11/16/2023,IT/QuangHT,NaN,NaN,NaN,_x000D_\n_x000D_\n,Hướng dẫn Cập nhật Flow tạo task nội bộ,NaN
581,WL6avO-H60-KXHYty1PWsckAFE9B,"GSC, JJS",Completed,Medium,IT/QuangHT,IT/QuangHT,11/15/2023,NaN,11/15/2023,False,False,11/15/2023,IT/QuangHT,0/2,"Remove App redirect lạ, remove code redirect t...",NaN,"_x000D_\nLỗi website redirect, restart site nà...",Hướng dẫn fix lỗi webserver GSC,NaN
582,j8pQ8TdUNUyFtEl6uhJvJskAMaDo,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/13/2023,11/15/2023,11/15/2023,False,False,11/15/2023,IT/TuanPA,0/3,Webex;Mr An/XDHT;PH Đào tạo L21 - 14h00,Light blue,_x000D_\n* Yêu cầu bởi: IT/TuanPA _x000D_\n_x...,TID: ff7c36,Họp ban Projection Tập Đoàn và Gemalink
583,pddz1SYqSEeeYL8fX9EC8MkAOdR8,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/14/2023,11/15/2023,11/15/2023,False,False,11/15/2023,IT/TuanPA,0/3,Webex;PH Đào tạo L21 - 10h00;Ms Hoài Anh/GSC,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...,,GSC- Projection Meeting
584,jBRl031jHkOba265c30ML8kAPAY5,Meeting Support,Completed,Medium,IT/TuanPA,Gemadept IT Helpdesk,11/14/2023,11/15/2023,11/15/2023,False,False,11/15/2023,IT/TuanPA,0/3,Ms Trúc/GSC;PH lầu 20 - 8h30;Webex,Light blue,_x000D_\nGhi chú từ người thực hiện công việc:...,,HỌP - MLOS - OPS- CAM/ sáng thứ ngày //

In [88]:
df['Task name'] = df['First Name'] + df['Last Name'].astype(str)

In [91]:
df=df.drop('First Name',axis=1)

In [92]:
df=df.drop('Last Name',axis=1)

In [93]:
df

,Task ID,Bucket Name,Progress,Priority,Assigned To,Created By,Created Date,Start Date,Due Date,Is Recurring,Late,Completed Date,Completed By,Completed Checklist Items,Checklist Items,Labels,Description,Task name
0,yZ7MKKmfmkW7F17FpQk7pMkAAldv,Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/08/2024,False,False,NaN,NaN,0/3,Ms Thắm/GLC;PH Đào tạo L21 - 9h30;H.323,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...,GLC HỌP THÁNG DUC THÁNG .
1,_98BmlWNSky-H-3b7cJphskAP0si,Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/26/2024,02/26/2024,02/27/2024,False,False,NaN,NaN,NaN,NaN,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...,Họp review phần ngôn ngữ tiếng Anh trên websi...
2,RsSYhYMSSEevknM1lziKd8kADSNi,Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/01/2024,False,False,NaN,NaN,0/3,Webex;Ms Vân/R&D;PH ??? - 14h00,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...,Họp TF dự án trồng rừng
3,DLIpJNhmqkiqfgUEt8AZtckALkzn,Waitlist,In progress,Medium,NaN,Gemadept IT Helpdesk,02/25/2024,02/24/2024,02/25/2024,False,True,NaN,NaN,NaN,NaN,Red,Ghi chú:\n\n###\n* Yêu cầu bởi: GLCIT/Trinh.Ph...,<pepsict>Kiểm tra email
4,ghL0FByfsEWVIkGqKmMwlckADD7g,Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/23/2024,02/23/2024,02/24/2024,False,True,NaN,NaN,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: antv@cehsoft.c...,[Smartport] Triển khai dịch vụ bảo trì SMP và...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1177,LTeUWl3LvESweZF9C2RgJskALj7C,MS 365,Completed,Medium,IT/QuangHT,IT/QuangHT,08/18/2023,08/16/2023,08/17/2023,False,False,08/18/2023,IT/QuangHT,0/2,"Training ITHO;Tạo plan IT Operation, add Team ...",NaN,NaN,Triển khai Planner phòng ITHOnan
1178,z6MFfU4IMUa7nAICaxenCskADUvx,"Network,Server/Firewall,ATTT",Completed,Medium,IT/DatTQ;IT/TuanPA,ITHO/CangPT,08/17/2023,NaN,08/18/2023,False,False,08/17/2023,IT/QuangHT,NaN,NaN,NaN,_x000D_\n_x000D_\n,Rà soát sắp xếp lại Rack phòng Server
1179,c0-k_AfbBESoHO_29U4WN8kABsdq,SmartPort,Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,NaN,08/15/2023,False,False,08/15/2023,IT/QuangHT,0/2,Hướng dẫn tính năng sFTP;Bộ quy trình mẫu,NaN,NaN,Hướng dẫn quy trình kết nối EDO cho IT PIP/BDPnan
1180,5ZMM9GC86UG8T1x9UfEFLckAN6NQ,"Moodle, Đào tạo, Event",Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,NaN,08/15/2023,False,False,08/15/2023,IT/QuangHT,NaN,NaN,NaN,NaN,Hướng dẫn TTS thay đổi giao diện cài đặt plugi...
1181,8UsYELtkfk2CDuyKjHMj6MkAJpVX,"Moodle, Đào tạo, Event",Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,08/08/2023,08/11/2023,False,False,08/15/2023,IT/QuangHT,0/4,Lập kế hoạch;Tạo slide trình chiếu;Gởi thư mời...,NaN,NaN,Triển khai WS Lập kế hoạch với Ms Plannernan

In [99]:
Emails=['DatTQ@gemadept.com.vn','HuyTP@gemadept.com.vn','LocCQ@gemadept.com.vn','NhutNDQ@gemadept.com.vn','QuangHT@gemadept.com.vn','thaitd@gemadept.com.vn','TuanCQ@gemadept.com.vn','tuanpa@gemadept.com.vn','cangpt@gemadept.com.vn','DatTQ2@gemadept.com.vn','LuanNVM@gemadept.com.vn']

df['Email']=Emails

ValueError: Length of values (11) does not match length of index (1182)

In [100]:
df['Email'] = 'example@gemadept.com.vn'

In [101]:
df

,Task ID,Bucket Name,Progress,Priority,Assigned To,Created By,Created Date,Start Date,Due Date,Is Recurring,Late,Completed Date,Completed By,Completed Checklist Items,Checklist Items,Labels,Description,Task name,Email
0,yZ7MKKmfmkW7F17FpQk7pMkAAldv,Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/08/2024,False,False,NaN,NaN,0/3,Ms Thắm/GLC;PH Đào tạo L21 - 9h30;H.323,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...,GLC HỌP THÁNG DUC THÁNG .,example@gemadept.com.vn
1,_98BmlWNSky-H-3b7cJphskAP0si,Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/26/2024,02/26/2024,02/27/2024,False,False,NaN,NaN,NaN,NaN,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...,Họp review phần ngôn ngữ tiếng Anh trên websi...,example@gemadept.com.vn
2,RsSYhYMSSEevknM1lziKd8kADSNi,Meeting Support,In progress,Medium,IT/TuanPA,Gemadept IT Helpdesk,02/26/2024,02/26/2024,03/01/2024,False,False,NaN,NaN,0/3,Webex;Ms Vân/R&D;PH ??? - 14h00,Light blue,Ghi chú:_x000D_\n_x000D_\n###_x000D_\n* Yêu cầ...,Họp TF dự án trồng rừng,example@gemadept.com.vn
3,DLIpJNhmqkiqfgUEt8AZtckALkzn,Waitlist,In progress,Medium,NaN,Gemadept IT Helpdesk,02/25/2024,02/24/2024,02/25/2024,False,True,NaN,NaN,NaN,NaN,Red,Ghi chú:\n\n###\n* Yêu cầu bởi: GLCIT/Trinh.Ph...,<pepsict>Kiểm tra email,example@gemadept.com.vn
4,ghL0FByfsEWVIkGqKmMwlckADD7g,Ticket,In progress,Medium,IT/QuangHT,Gemadept IT Helpdesk,02/23/2024,02/23/2024,02/24/2024,False,True,NaN,NaN,NaN,NaN,Light blue,Ghi chú:\n\n###\n* Yêu cầu bởi: antv@cehsoft.c...,[Smartport] Triển khai dịch vụ bảo trì SMP và...,example@gemadept.com.vn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1177,LTeUWl3LvESweZF9C2RgJskALj7C,MS 365,Completed,Medium,IT/QuangHT,IT/QuangHT,08/18/2023,08/16/2023,08/17/2023,False,False,08/18/2023,IT/QuangHT,0/2,"Training ITHO;Tạo plan IT Operation, add Team ...",NaN,NaN,Triển khai Planner phòng ITHOnan,example@gemadept.com.vn
1178,z6MFfU4IMUa7nAICaxenCskADUvx,"Network,Server/Firewall,ATTT",Completed,Medium,IT/DatTQ;IT/TuanPA,ITHO/CangPT,08/17/2023,NaN,08/18/2023,False,False,08/17/2023,IT/QuangHT,NaN,NaN,NaN,_x000D_\n_x000D_\n,Rà soát sắp xếp lại Rack phòng Server,example@gemadept.com.vn
1179,c0-k_AfbBESoHO_29U4WN8kABsdq,SmartPort,Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,NaN,08/15/2023,False,False,08/15/2023,IT/QuangHT,0/2,Hướng dẫn tính năng sFTP;Bộ quy trình mẫu,NaN,NaN,Hướng dẫn quy trình kết nối EDO cho IT PIP/BDPnan,example@gemadept.com.vn
1180,5ZMM9GC86UG8T1x9UfEFLckAN6NQ,"Moodle, Đào tạo, Event",Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,NaN,08/15/2023,False,False,08/15/2023,IT/QuangHT,NaN,NaN,NaN,NaN,Hướng dẫn TTS thay đổi giao diện cài đặt plugi...,example@gemadept.com.vn
1181,8UsYELtkfk2CDuyKjHMj6MkAJpVX,"Moodle, Đào tạo, Event",Completed,Medium,IT/QuangHT,IT/QuangHT,08/15/2023,08/08/2023,08/11/2023,False,False,08/15/2023,IT/QuangHT,0/4,Lập kế hoạch;Tạo slide trình chiếu;Gởi thư mời...,NaN,NaN,Triển khai WS Lập kế hoạch với Ms Plannernan,example@gemadept.com.vn

In [94]:
df.to_excel('C:\\Users\\buidu\\OneDrive\\Máy tính\\thisCode\\code\\PYthon_only\\task2\\newrp.xlsx', index=False)